apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: inference-api-alb-permissive
  namespace: inference
spec:
  selector:
    matchLabels:
      app: inference-api
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: inference-api-alb-permissive
  namespace: inference
spec:
  selector:
    matchLabels:
      app: inference-api
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: dashboard-frontend-alb-permissive
  namespace: app
spec:
  selector:
    matchLabels:
      app: dashboard-frontend
  mtls:
    mode: PERMISSIVE
