import os
from datetime import datetime, timezone

import requests
from fastapi import FastAPI, Header, HTTPException, Request

app = FastAPI(title="Bastion Alert Relay")

SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")
RELAY_TOKEN = os.getenv("RELAY_TOKEN")
SUMMARY_LIMIT = 2500

STATUS_META = {
    "success": {
        "title": "CI/CD Success Alert",
        "icon": "✅",
        "color": "#2EB67D",
    },
    "failed": {
        "title": "CI/CD Failure Alert",
        "icon": "🚨",
        "color": "#E01E5A",
    },
    "warning": {
        "title": "CI/CD Warning Alert",
        "icon": "⚠️",
        "color": "#ECB22E",
    },
}
DEFAULT_STATUS_META = {
    "title": "CI/CD Pipeline Event",
    "icon": "ℹ️",
    "color": "#1D9BD1",
}


def normalize_status(payload: dict) -> str:
    return str(payload.get("status") or "failed").strip().lower()


def get_status_meta(status: str) -> dict:
    return STATUS_META.get(status, DEFAULT_STATUS_META)


def resolve_summary(payload: dict) -> str:
    summary = payload.get("summary") or payload.get("error_summary")
    if not summary:
        return "No summary provided. Check the GitLab pipeline log."
    return str(summary)[:SUMMARY_LIMIT]


def is_usable_url(value: str | None) -> bool:
    return bool(value and value not in {"unknown", "None"})


def render_slack_message(payload: dict) -> dict:
    status = normalize_status(payload)
    meta = get_status_meta(status)
    occurred_at = str(
        payload.get("occurred_at")
        or payload.get("created_at")
        or datetime.now(timezone.utc).isoformat()
    )
    pipeline_url = str(payload.get("pipeline_url", ""))
    job_url = str(payload.get("job_url", ""))
    summary = resolve_summary(payload)

    fields = [
        {"type": "mrkdwn", "text": f"*Project:*\n{payload.get('project', 'unknown')}"},
        {
            "type": "mrkdwn",
            "text": f"*Project Path:*\n`{payload.get('project_path', 'unknown')}`",
        },
        {"type": "mrkdwn", "text": f"*Job:*\n{payload.get('job', 'unknown')}"},
        {"type": "mrkdwn", "text": f"*Stage:*\n{payload.get('stage', 'unknown')}"},
        {"type": "mrkdwn", "text": f"*Status:*\n{status}"},
        {"type": "mrkdwn", "text": f"*Branch:*\n{payload.get('branch', 'unknown')}"},
        {"type": "mrkdwn", "text": f"*Commit:*\n{payload.get('commit', 'unknown')}"},
        {"type": "mrkdwn", "text": f"*Occurred At:*\n{occurred_at}"},
    ]

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"{meta['icon']} {meta['title']}",
            },
        },
        {
            "type": "section",
            "fields": fields,
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*Pipeline URL:*\n{pipeline_url or 'N/A'}\n\n"
                    f"*Job URL:*\n{job_url or 'N/A'}"
                ),
            },
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Summary:*\n```{summary}```",
            },
        },
    ]

    action_elements: list[dict] = []
    if is_usable_url(pipeline_url):
        action_elements.append(
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "Open Pipeline"},
                "url": pipeline_url,
            }
        )
    if is_usable_url(job_url):
        action_elements.append(
            {
                "type": "button",
                "text": {"type": "plain_text", "text": "Open Job Log"},
                "url": job_url,
            }
        )
    if action_elements:
        blocks.append({"type": "actions", "elements": action_elements})

    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Generated by Bastion Alert Relay at {occurred_at}",
                }
            ],
        }
    )

    return {
        "text": f"{meta['icon']} {meta['title']} - {payload.get('project', 'unknown')}",
        "attachments": [
            {
                "color": meta["color"],
                "blocks": blocks,
            }
        ],
    }


def validate_configuration() -> None:
    if not SLACK_WEBHOOK_URL:
        raise HTTPException(status_code=500, detail="SLACK_WEBHOOK_URL is not set")
    if not RELAY_TOKEN:
        raise HTTPException(status_code=500, detail="RELAY_TOKEN is not set")


def validate_token(x_relay_token: str | None) -> None:
    if x_relay_token != RELAY_TOKEN:
        raise HTTPException(status_code=401, detail="invalid relay token")


def send_slack_event(payload: dict) -> dict:
    slack_message = render_slack_message(payload)

    try:
        response = requests.post(
            SLACK_WEBHOOK_URL,
            json=slack_message,
            timeout=5,
        )
        response.raise_for_status()
    except requests.RequestException as exc:
        raise HTTPException(
            status_code=502,
            detail=f"failed to send slack alert: {exc}",
        )

    return {
        "status": "sent",
        "project": payload.get("project", "unknown"),
        "job": payload.get("job", "unknown"),
    }


async def handle_ci_event(
    request: Request,
    x_relay_token: str | None,
    default_status: str | None = None,
) -> dict:
    validate_configuration()
    validate_token(x_relay_token)

    payload = await request.json()
    if default_status and not payload.get("status"):
        payload["status"] = default_status
    payload.setdefault("occurred_at", datetime.now(timezone.utc).isoformat())

    return send_slack_event(payload)


@app.get("/health")
def health():
    return {
        "status": "ok",
        "service": "alert-relay",
    }


@app.post("/ci-event")
async def ci_event(
    request: Request,
    x_relay_token: str | None = Header(default=None),
):
    return await handle_ci_event(request, x_relay_token)


@app.post("/ci-failure")
async def ci_failure(
    request: Request,
    x_relay_token: str | None = Header(default=None),
):
    return await handle_ci_event(request, x_relay_token, default_status="failed")
