apiVersion: batch/v1
kind: Job
metadata:
  name: nvidia-smi-validation
  namespace: gpu-workload
  labels:
    app.kubernetes.io/name: nvidia-smi-validation
    app.kubernetes.io/part-of: hybrid-ai-serving-platform
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nvidia-smi-validation
    spec:
      restartPolicy: Never
      runtimeClassName: nvidia
      containers:
        - name: nvidia-smi
          image: nvidia/cuda:12.4.1-base-ubuntu22.04
          command: ["nvidia-smi"]
          resources:
            limits:
              nvidia.com/gpu: "1"
