apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-validation
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        hybrid-ai.io/node-role: gpu-worker
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      runtimeClassName: nvidia
      containers:
        - name: nvidia-smi
          image: nvidia/cuda:12.2.0-base-ubuntu22.04
          command: ["nvidia-smi"]
          resources:
            limits:
              nvidia.com/gpu: "1"
