runtimeClassName: nvidia
migStrategy: none
failOnInitError: true
nodeSelector:
  hybrid-ai.io/accelerator: nvidia
  hybrid-ai.io/node-role: gpu-worker
tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
