controllerManager:
  nodeSelector:
    workload: system

dashboard:
  create: true
  nodeSelector:
    workload: system

dnsServer:
  nodeSelector:
    workload: system

chaosDaemon:
  runtime: containerd
  socketPath: /run/containerd/containerd.sock
