apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pdb.yaml
  - podmonitor.yaml
  - scaledobject.yaml
  - serviceaccount.yaml
  - trigger-auth.yaml

images:
  - name: 808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/inference-worker
    newName: 808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/inference-worker
    newTag: latest
