apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-predictor
  namespace: hasp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kserve-predictor
  template:
    metadata:
      labels:
        app: kserve-predictor
    spec:
      containers:
        - name: kserve-predictor
          image: 808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/kserve-predictor:latest
          ports:
            - containerPort: 8080
