apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: inference
data:
  APP_ENV: production
  AWS_REGION: ap-northeast-2
  PREDICTOR_URL: http://predictor-predictor-default.inference.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: inference
data:
  BOOTSTRAP_SERVERS: "replace-me:9092"
  REQUEST_TOPIC: inference-requests
  RESULT_TOPIC: inference-results
  CONSUMER_GROUP: inference-workers
  RESULT_CONSUMER_GROUP: result-consumers
  DYNAMODB_TABLE_NAME: replace-me
