apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-api-sa
  namespace: inference
  annotations: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: inference
  annotations: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: predictor-sa
  namespace: inference
  annotations: {}
