apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-api
  namespace: hasp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-api
  template:
    metadata:
      labels:
        app: inference-api
    spec:
      containers:
        - name: inference-api
          image: 808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/inference-api:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: replace-me:9092
            - name: REQUEST_TOPIC
              value: inference-request
          ports:
            - containerPort: 8080
