apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sre-slack-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: sre-monitoring
spec:
  route:
    receiver: infra-alerts
    groupBy: ['alertname', 'namespace', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    routes:
      - receiver: slo-alerts
        matchers:
          - name: team
            matchType: "="
            value: sre
  receivers:
    - name: infra-alerts
      slackConfigs:
        - apiURL:
            name: slack-webhooks
            key: infra
          channel: '#infra-alerts'
          title: '{{ if eq .GroupLabels.severity "critical" }}[INFRA][CRITICAL]{{ else }}[INFRA][WARNING]{{ end }} {{ .GroupLabels.alertname }}'
          text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'
          sendResolved: true
    - name: slo-alerts
      slackConfigs:
        - apiURL:
            name: slack-webhooks
            key: slo
          channel: '#slo-alerts'
          title: '{{ if eq .GroupLabels.severity "critical" }}[SLO][CRITICAL]{{ else }}[SLO][WARNING]{{ end }} {{ .GroupLabels.alertname }}'
          text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'
          sendResolved: true
