---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-tenant
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: hybrid-ai
  namespace: minio-tenant
spec:
  image: minio/minio:RELEASE.2024-05-10T01-41-38Z
  imagePullPolicy: IfNotPresent
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  configuration:
    name: minio-configuration
  requestAutoCert: false
  features:
    bucketDNS: false
  buckets:
    - name: models
      objectLock: false
      region: us-east-1
    - name: datasets
      objectLock: false
      region: us-east-1
    - name: artifacts
      objectLock: false
      region: us-east-1
  users:
    - name: model-admin
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: minio-tenant
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30990
      protocol: TCP
      name: console
  selector:
    v1.min.io/tenant: hybrid-ai
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: minio-tenant
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900
      protocol: TCP
      name: s3
  selector:
    v1.min.io/tenant: hybrid-ai
