apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: inference-api=808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/inference-api
    argocd-image-updater.argoproj.io/inference-api.update-strategy: newest-build
    argocd-image-updater.argoproj.io/inference-api.allow-tags: regexp:^[a-f0-9]{40}$
    argocd-image-updater.argoproj.io/inference-api.force-update: "true"
    argocd-image-updater.argoproj.io/inference-api.kustomize.image-name: 808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/inference-api
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      name: inference-api
      namespace: inference
      jsonPointers:
        - /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
  source:
    repoURL: https://github.com/SGS-Strategy/hybrid-ai-serving-platform.git
    targetRevision: main
    path: public/k8s/apps/inference-api
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
