apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: ghcr.io/kserve/charts
    chart: kserve-crd
    targetRevision: v0.17.0
    helm:
      releaseName: kserve-crd
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

