apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: default
  source:
    repoURL: ghcr.io/kserve/charts
    chart: kserve-resources
    targetRevision: v0.17.0
    helm:
      releaseName: kserve
      valuesObject:
        kserve:
          controller:
            deploymentMode: Standard
            nodeSelector:
              workload: general
          ingress:
            disableIstioVirtualHost: true
            disableIngressCreation: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

