apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-app.yaml
  - aws-load-balancer-controller-app.yaml
  - metrics-server-app.yaml
  - keda-app.yaml
  - kube-prometheus-stack-app.yaml
  - loki-app.yaml
  - promtail-app.yaml
  - chaos-mesh-app.yaml
  - kserve-crds-app.yaml
  - kserve-app.yaml
