apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base-app.yaml
  - policy-app.yaml
  - cert-manager-app.yaml
  - argocd-image-updater-app.yaml
  - istio-base-app.yaml
  - istiod-app.yaml
  - istio-cni-app.yaml
  - ztunnel-app.yaml
  - inference-api-app.yaml
  - inference-worker-app.yaml
  - metrics-server-app.yaml
  - keda-app.yaml
  - kube-prometheus-stack-app.yaml
  - loki-app.yaml
  - promtail-app.yaml
  - chaos-mesh-app.yaml
  - kserve-crds-app.yaml
  - kserve-app.yaml
  - pdm-serving-app.yaml
  - dashboard-backend-app.yaml
  - dashboard-frontend-app.yaml
