apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdm-serving
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"

    argocd-image-updater.argoproj.io/image-list: predictive-model=808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/predictive-model
    argocd-image-updater.argoproj.io/predictive-model.update-strategy: newest-build
    argocd-image-updater.argoproj.io/predictive-model.allow-tags: regexp:^v[0-9]+\\.[0-9]+\\.[0-9]+$
    argocd-image-updater.argoproj.io/predictive-model.force-update: "true"
    argocd-image-updater.argoproj.io/predictive-model.kustomize.image-name: 808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/predictive-model

    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-github-app-creds
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/SGS-Strategy/hybrid-ai-serving-platform.git
    targetRevision: main
    path: public/k8s/serving/predictive-model
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
