apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-consumer
  namespace: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-consumer
  template:
    metadata:
      labels:
        app: result-consumer
    spec:
      serviceAccountName: worker-sa
      nodeSelector:
        workload: app
      containers:
        - name: result-consumer
          image: 808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/result-consumer:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - configMapRef:
                name: kafka-config
            - secretRef:
                name: api-secret
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
