---
cert_manager_namespace: cert-manager
cert_manager_release_name: cert-manager
cert_manager_chart_ref: oci://quay.io/jetstack/charts/cert-manager
cert_manager_chart_version: v1.20.2
cert_manager_helm_timeout: 10m0s

kserve_namespace: kserve
kserve_crd_release_name: kserve-crd
kserve_crd_chart_ref: oci://ghcr.io/kserve/charts/kserve-crd
kserve_release_name: kserve
kserve_chart_ref: oci://ghcr.io/kserve/charts/kserve-resources
kserve_chart_version: v0.18.0
kserve_helm_timeout: 10m0s
kserve_ingress_class_name: alb
