apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pdm-isvc.yaml
  - pdb.yaml
images:
  - name: 808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/predictive-model
    newName: 808379768010.dkr.ecr.ap-northeast-2.amazonaws.com/predictive-model
    newTag: v1.0.8
