apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pdm-predictor
  namespace: inference
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: pdm
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
